src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TeamRepository::class)]
class Team
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $team_name = null;

    /**
     * @var Collection<int, Tournament>
     */
    #[ORM\ManyToMany(targetEntity: Tournament::class, mappedBy: 'team')]
    private Collection $teams;

    /**
     * @var Collection<int, Score>
     */
    #[ORM\OneToMany(targetEntity: Score::class, mappedBy: 'team')]
    private Collection $scores;

    #[ORM\ManyToOne(inversedBy: 'team')]
    private ?Ranking $ranking = null;

    /**
     * @var Collection<int, Phase>
     */
    #[ORM\OneToMany(targetEntity: Phase::class, mappedBy: 'team')]
    private Collection $phases;

    #[ORM\ManyToOne(inversedBy: 'teams')]
    private ?Player $player = null;

    /**
     * @var Collection<int, Point>
     */
    #[ORM\OneToMany(targetEntity: Point::class, mappedBy: 'team')]
    private Collection $point;

    public function __construct()
    {
        $this->teams = new ArrayCollection();
        $this->scores = new ArrayCollection();
        $this->phases = new ArrayCollection();
        $this->point = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTeamName(): ?string
    {
        return $this->team_name;
    }

    public function setTeamName(string $team_name): static
    {
        $this->team_name = $team_name;

        return $this;
    }

    /**
     * @return Collection<int, Tournament>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function addTeam(Tournament $team): static
    {
        if (!$this->teams->contains($team)) {
            $this->teams->add($team);
            $team->addTeam($this);
        }

        return $this;
    }

    public function removeTeam(Tournament $team): static
    {
        if ($this->teams->removeElement($team)) {
            $team->removeTeam($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Score>
     */
    public function getScores(): Collection
    {
        return $this->scores;
    }

    public function addScore(Score $score): static
    {
        if (!$this->scores->contains($score)) {
            $this->scores->add($score);
            $score->setTeam($this);
        }

        return $this;
    }

    public function removeScore(Score $score): static
    {
        if ($this->scores->removeElement($score)) {
            // set the owning side to null (unless already changed)
            if ($score->getTeam() === $this) {
                $score->setTeam(null);
            }
        }

        return $this;
    }

    public function getRanking(): ?Ranking
    {
        return $this->ranking;
    }

    public function setRanking(?Ranking $ranking): static
    {
        $this->ranking = $ranking;

        return $this;
    }

    /**
     * @return Collection<int, Phase>
     */
    public function getPhases(): Collection
    {
        return $this->phases;
    }

    public function addPhase(Phase $phase): static
    {
        if (!$this->phases->contains($phase)) {
            $this->phases->add($phase);
            $phase->setTeam($this);
        }

        return $this;
    }

    public function removePhase(Phase $phase): static
    {
        if ($this->phases->removeElement($phase)) {
            // set the owning side to null (unless already changed)
            if ($phase->getTeam() === $this) {
                $phase->setTeam(null);
            }
        }

        return $this;
    }

    public function getPlayer(): ?Player
    {
        return $this->player;
    }

    public function setPlayer(?Player $player): static
    {
        $this->player = $player;

        return $this;
    }

    /**
     * @return Collection<int, Point>
     */
    public function getPoint(): Collection
    {
        return $this->point;
    }

    public function addPoint(Point $point): static
    {
        if (!$this->point->contains($point)) {
            $this->point->add($point);
            $point->setTeam($this);
        }

        return $this;
    }

    public function removePoint(Point $point): static
    {
        if ($this->point->removeElement($point)) {
            // set the owning side to null (unless already changed)
            if ($point->getTeam() === $this) {
                $point->setTeam(null);
            }
        }

        return $this;
    }
}

src/Form/TeamType.php
<?php

namespace App\Form;

use App\Entity\Player;
use App\Entity\Ranking;
use App\Entity\Team;
use App\Entity\Tournament;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TeamType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('team_name')
            ->add('teams', EntityType::class, [
                'class' => Tournament::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
            ->add('ranking', EntityType::class, [
                'class' => Ranking::class,
                'choice_label' => 'id',
            ])
            ->add('player', EntityType::class, [
                'class' => Player::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Team::class,
        ]);
    }
}

src/Controller/TeamController.php
<?php

namespace App\Controller;

use App\Entity\Team;
use App\Form\TeamType;
use App\Repository\TeamRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/team')]
class TeamController extends AbstractController
{
    #[Route('/', name: 'app_team_index', methods: ['GET'])]
    public function index(TeamRepository $teamRepository): Response
    {
        return $this->render('team/index.html.twig', [
            'teams' => $teamRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_team_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $team = new Team();
        $form = $this->createForm(TeamType::class, $team);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($team);
            $entityManager->flush();

            return $this->redirectToRoute('app_team_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('team/new.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_team_show', methods: ['GET'])]
    public function show(Team $team): Response
    {
        return $this->render('team/show.html.twig', [
            'team' => $team,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_team_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Team $team, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TeamType::class, $team);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_team_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('team/edit.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_team_delete', methods: ['POST'])]
    public function delete(Request $request, Team $team, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$team->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($team);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_team_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/team/_delete_form.html.twig
<form method="post" action="{{ path('app_team_delete', {'id': team.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ team.id) }}">
    <button class="btn">Delete</button>
</form>

templates/team/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/team/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Team{% endblock %}

{% block body %}
    <h1>Edit Team</h1>

    {{ include('team/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_team_index') }}">back to list</a>

    {{ include('team/_delete_form.html.twig') }}
{% endblock %}

templates/team/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Team index{% endblock %}

{% block body %}
<div class="grid-content">
    <h1>Gestion des du tournois </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Team_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for team in teams %}
            <tr>
                <td>{{ team.id }}</td>
                <td>{{ team.teamName }}</td>
                <td>
                    <a href="{{ path('app_team_show', {'id': team.id}) }}">show</a>
                    <a href="{{ path('app_team_edit', {'id': team.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

    <a href="{{ path('app_team_new') }}">Create new</a>
{% endblock %}

templates/team/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Team{% endblock %}

{% block body %}
<div class="grid-content">
    <h1>Create new Team</h1>

    {{ include('team/_form.html.twig') }}
    
</div>
    <a href="{{ path('app_team_index') }}">back to list</a>
{% endblock %}

templates/team/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Team{% endblock %}

{% block body %}
    <h1>Team</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ team.id }}</td>
            </tr>
            <tr>
                <th>Team_name</th>
                <td>{{ team.teamName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_team_index') }}">back to list</a>

    <a href="{{ path('app_team_edit', {'id': team.id}) }}">edit</a>

    {{ include('team/_delete_form.html.twig') }}
{% endblock %}