src/Entity/Tournament.php
<?php

namespace App\Entity;

use App\Repository\TournamentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TournamentRepository::class)]
class Tournament
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name_tournament = null;

    #[ORM\Column(length: 100)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(length: 100)]
    private ?string $gender = null;

    #[ORM\Column(length: 100)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'sports')]
    private ?Sport $sport = null;

    /**
     * @var Collection<int, Team>
     */
    #[ORM\ManyToMany(targetEntity: Team::class, inversedBy: 'teams')]
    private Collection $team;

    /**
     * @var Collection<int, Meetings>
     */
    #[ORM\OneToMany(targetEntity: Meetings::class, mappedBy: 'tournament')]
    private Collection $meetings;

    public function __construct()
    {
        $this->team = new ArrayCollection();
        $this->meetings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameTournament(): ?string
    {
        return $this->name_tournament;
    }

    public function setNameTournament(string $name_tournament): static
    {
        $this->name_tournament = $name_tournament;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getSport(): ?Sport
    {
        return $this->sport;
    }

    public function setSport(?Sport $sport): static
    {
        $this->sport = $sport;

        return $this;
    }

    /**
     * @return Collection<int, Team>
     */
    public function getTeam(): Collection
    {
        return $this->team;
    }

    public function addTeam(Team $team): static
    {
        if (!$this->team->contains($team)) {
            $this->team->add($team);
        }

        return $this;
    }

    public function removeTeam(Team $team): static
    {
        $this->team->removeElement($team);

        return $this;
    }

    /**
     * @return Collection<int, Meetings>
     */
    public function getMeetings(): Collection
    {
        return $this->meetings;
    }

    public function addMeeting(Meetings $meeting): static
    {
        if (!$this->meetings->contains($meeting)) {
            $this->meetings->add($meeting);
            $meeting->setTournament($this);
        }

        return $this;
    }

    public function removeMeeting(Meetings $meeting): static
    {
        if ($this->meetings->removeElement($meeting)) {
            // set the owning side to null (unless already changed)
            if ($meeting->getTournament() === $this) {
                $meeting->setTournament(null);
            }
        }

        return $this;
    }
}

src/Form/TournamentType.php
<?php

namespace App\Form;

use App\Entity\Sport;
use App\Entity\Team;
use App\Entity\Tournament;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TournamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_tournament')
            ->add('description')
            ->add('start_date', null, [
                'widget' => 'single_text',
            ])
            ->add('end_date', null, [
                'widget' => 'single_text',
            ])
            ->add('gender')
            ->add('status')
            ->add('sport', EntityType::class, [
                'class' => Sport::class,
                'choice_label' => 'id',
            ])
            ->add('team', EntityType::class, [
                'class' => Team::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tournament::class,
        ]);
    }
}

src/Controller/TournamentController.php
<?php

namespace App\Controller;

use App\Entity\Tournament;
use App\Form\TournamentType;
use App\Repository\TournamentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/tournament')]
class TournamentController extends AbstractController
{
    #[Route('/', name: 'app_tournament_index', methods: ['GET'])]
    public function index(TournamentRepository $tournamentRepository): Response
    {
        return $this->render('tournament/index.html.twig', [
            'tournaments' => $tournamentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_tournament_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $tournament = new Tournament();
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($tournament);
            $entityManager->flush();

            return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournament/new.html.twig', [
            'tournament' => $tournament,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tournament_show', methods: ['GET'])]
    public function show(Tournament $tournament): Response
    {
        return $this->render('tournament/show.html.twig', [
            'tournament' => $tournament,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tournament_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tournament $tournament, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournament/edit.html.twig', [
            'tournament' => $tournament,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tournament_delete', methods: ['POST'])]
    public function delete(Request $request, Tournament $tournament, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tournament->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($tournament);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tournament/_delete_form.html.twig
<form method="post" action="{{ path('app_tournament_delete', {'id': tournament.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournament.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tournament/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tournament/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tournament{% endblock %}

{% block body %}
    <h1>Edit Tournament</h1>

    {{ include('tournament/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_tournament_index') }}">back to list</a>

    {{ include('tournament/_delete_form.html.twig') }}
{% endblock %}

templates/tournament/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament index{% endblock %}

{% block body %}
<div class="grid-content">
    <h1>Gestion des tournois sportifs</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_tournament</th>
                <th>Description</th>
                <th>Start_date</th>
                <th>End_date</th>
                <th>Gender</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tournament in tournaments %}
            <tr>
                <td>{{ tournament.id }}</td>
                <td>{{ tournament.nameTournament }}</td>
                <td>{{ tournament.description }}</td>
                <td>{{ tournament.startDate ? tournament.startDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ tournament.endDate ? tournament.endDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ tournament.gender }}</td>
                <td>{{ tournament.status }}</td>
                <td>
                    <a href="{{ path('app_tournament_show', {'id': tournament.id}) }}">show</a>
                    <a href="{{ path('app_tournament_edit', {'id': tournament.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

    <a href="{{ path('app_tournament_new') }}">Create new</a>
{% endblock %}

templates/tournament/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tournament{% endblock %}

{% block body %}
<div class="grid-content">
    <h1>Créer un nouveau tournois</h1>

    {{ include('tournament/_form.html.twig') }}
</div>

    <a href="{{ path('app_tournament_index') }}">back to list</a>
{% endblock %}

templates/tournament/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament{% endblock %}

{% block body %}
<div class="grid-content">
    <h1>Gestion du Tournois</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tournament.id }}</td>
            </tr>
            <tr>
                <th>Name_tournament</th>
                <td>{{ tournament.nameTournament }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ tournament.description }}</td>
            </tr>
            <tr>
                <th>Start_date</th>
                <td>{{ tournament.startDate ? tournament.startDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ tournament.endDate ? tournament.endDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ tournament.gender }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ tournament.status }}</td>
            </tr>
        </tbody>
    </table>
</div>

    <a href="{{ path('app_tournament_index') }}">back to list</a>

    <a href="{{ path('app_tournament_edit', {'id': tournament.id}) }}">edit</a>

    {{ include('tournament/_delete_form.html.twig') }}
{% endblock %}